routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();
Auth::routes(['verify' => true]);

Route::get('/', 'HomeController@index')->name('dashboard');

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'verified']], function() {
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');        
    Route::resource('products','ProductController');
    
    Route::post('settings/upload', 'SettingController@upload')->name('settings.upload');
    Route::resource('settings','SettingController');
    Route::post('products/upload', 'ProductController@upload')->name('products.upload');
    
    Route::get('perfil', 'UserController@profile')->name('profile');
    
    Route::group(['prefix' => 'network'], function() {
        Route::get('laterality', 'NetworkController@laterality')->name('network.laterality');        
        Route::get('create', 'NetworkController@create')->name('network.create');
        Route::post('store', 'NetworkController@store')->name('network.store');
        Route::get('distribution', 'NetworkController@distribution')->name('network.distribution');
        Route::get('sponsor', 'NetworkController@sponsor')->name('network.sponsor');
    });
});

resources/views/layouts/app.blade.php
<?php
    setlocale(LC_TIME, 'pt_BR', 'pt_BR.utf-8', 'pt_BR.utf-8', 'portuguese');
    date_default_timezone_set('America/Sao_Paulo');
    $hoje = strftime('%A, %d de %B de %Y', strtotime('today'));
?>
<!doctype html>
<html class="fixed sidebar-left-collapsed" lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    @include('layouts/head')
    <body>
        <section class="body">
            @include('layouts/header')
            <div class="inner-wrapper">
                @if(!Auth::guest())
                @include('layouts/sidebar')                
                @endif
                <section role="main" class="content-body pb-none">
                    @if(!Auth::guest())
                    <header class="page-header">
                        <h2>@yield('page_heading')</h2>
                        @yield('breadcrumb')
                    </header>
                    @endif
                    <!-- start: page -->
                    @if(session()->has('success'))
                    <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <strong>Sucesso!</strong><br>{{session('success')}}<br>
                    </div>
                    @endif

                    @yield('content')
                    <!-- end: page -->
                </section>
            </div>
            <aside id="sidebar-right" class="sidebar-right">
                <div class="nano">
                    <div class="nano-content">
                        <a href="#" class="mobile-close visible-xs">
                            Collapse <i class="fa fa-chevron-right"></i>
                        </a>

                        <div class="sidebar-right-wrapper">

                            <div class="sidebar-widget widget-calendar">
                                <h6>Data e hora</h6>
                                <div data-plugin-datepicker data-plugin-skin="dark" ></div>
                                <ul>
                                    <li>
                                        <time datetime="{{date('Y-m-d')}}T00:00+00:00">{{$hoje}}</time>
                                        <span class="icons icon-clock"></span> <span id="time"></span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </aside>

        </section>
        @include('layouts/footer')
    </body>
</html>

resources/views/layouts/footer.blade.php
        <!-- Vendor -->        
        <script src="{{asset('assets/vendor/jquery/jquery.js')}}"></script>
        <script src="{{asset('assets/vendor/primitive/js/jquery/jquery-ui-1.10.2.custom.min.js')}}"></script>
        <script src="{{asset('assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js')}}"></script>
        <script src="{{asset('assets/vendor/bootstrap/js/bootstrap.js')}}"></script>
        <script src="{{asset('assets/vendor/modernizr/modernizr.js')}}"></script>
        <script src="{{asset('assets/vendor/nanoscroller/nanoscroller.js')}}"></script>
        <script src="{{asset('assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js')}}"></script>
        <script src="{{asset('assets/vendor/magnific-popup/jquery.magnific-popup.js')}}"></script>
        <script src="{{asset('assets/vendor/jquery-placeholder/jquery-placeholder.js')}}"></script>

        <!-- Specific Page Vendor -->
        <script src="{{asset('assets/vendor/select2/js/select2.js')}}"></script>
        <script src="{{asset('assets/vendor/bootstrap-multiselect/bootstrap-multiselect.js')}}"></script>
        <script src="{{asset('assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.js')}}"></script>
        <script src="{{asset('assets/vendor/jquery-appear/jquery-appear.js')}}"></script>
        <script src="{{asset('assets/vendor/owl.carousel/owl.carousel.js')}}"></script>
        <script src="{{asset('assets/vendor/isotope/isotope.js')}}"></script>
        <script src="{{asset('assets/vendor/bootstrap-confirmation/bootstrap-confirmation.js')}}"></script>
        @yield('vendorscripts')
        @yield('modalconfirmscripts')
        <!-- Theme Base, Components and Settings -->
        <script src="{{asset('assets/javascripts/theme.js')}}"></script>

        <!-- Theme Custom -->
        <script src="{{asset('assets/javascripts/theme.custom.js')}}"></script>

        <!-- Theme Initialization Files -->
        <script src="{{asset('assets/javascripts/theme.init.js')}}"></script>

        <!-- Examples -->
        <script src="{{asset('assets/javascripts/dashboard/examples.landing.dashboard.js')}}"></script>
        <script src="{{asset('assets/javascripts/forms/examples.advanced.form.js')}}"></script>
        @yield('javascripts')

resources/views/layouts/head.blade.php
    <head>

        <!-- Basic -->
        <meta charset="UTF-8">
        
        <title>{{ getSetting('application_name') }}</title>
        <meta name="keywords" content="" />
        <meta name="description" content="">
        <meta name="author" content="odesenvolvedor.net">

        <!-- Mobile Metas -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

        <!-- Favicon -->
        <link rel="shortcut icon" href="{{asset('assets/images/' . getSetting('fav'))}}" />
        
        <!-- Web Fonts  -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

        <!-- Vendor CSS -->
        <link rel="stylesheet" href="{{asset('assets/vendor/bootstrap/css/bootstrap.css')}}" />
        <link rel="stylesheet" href="{{asset('assets/vendor/font-awesome/css/font-awesome.css')}}" />
        <link rel="stylesheet" href="{{asset('assets/vendor/simple-line-icons/css/simple-line-icons.css')}}">
        <link rel="stylesheet" href="{{asset('assets/vendor/magnific-popup/magnific-popup.css')}}" />
        <link rel="stylesheet" href="{{asset('assets/vendor/bootstrap-datepicker/css/bootstrap-datepicker3.css')}}" />        
        
        <!-- Specific Page Vendor CSS -->
        @yield('stylesheets')
        @yield('vendorstylesheets')
        <link rel="stylesheet" href="{{asset('assets/vendor/select2/css/select2.css')}}" />
	<link rel="stylesheet" href="{{asset('assets/vendor/select2-bootstrap-theme/select2-bootstrap.min.css')}}" />        
        <link rel="stylesheet" href="{{asset('assets/vendor/bootstrap-multiselect/bootstrap-multiselect.css')}}" />
        <link rel="stylesheet" href="{{asset('assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.css')}}" />
        <link rel="stylesheet" href="{{asset('assets/vendor/owl.carousel/assets/owl.carousel.css')}}" />
        <link rel="stylesheet" href="{{asset('assets/vendor/owl.carousel/assets/owl.theme.default.css')}}" />        
        <!-- Theme CSS -->
        <link rel="stylesheet" href="{{asset('assets/stylesheets/theme.css')}}" />

        <!-- Skin CSS -->
        <link rel="stylesheet" href="{{asset('assets/stylesheets/skins/default.css')}}" />

        <!-- Theme Custom CSS -->
        <link rel="stylesheet" href="{{asset('assets/stylesheets/theme-custom.css')}}">
    </head>

resources/views/layouts/header.blade.php
            <!-- start: header -->
            <header class="header">
                <div class="logo-container">
                    <a href="{{route('home')}}" class="logo">
                        <img src="{{asset('assets/images/' . getSetting('logo'))}}" height="35" alt="{{config('app.name')}}" />
                    </a>
                    <div class="visible-xs toggle-sidebar-left" data-toggle-class="sidebar-left-opened" data-target="html" data-fire-event="sidebar-left-opened">
                        <i class="fa fa-bars" aria-label="Toggle sidebar"></i>
                    </div>
                </div>

                @if(!Auth::guest())

                <!-- start: search & user box -->
                <div class="header-right">

                    <ul class="notifications">
<!--                        <li>
                            <a href="#" class="dropdown-toggle notification-icon" data-toggle="dropdown">
                                <i class="icons icon-people text-success"></i>
                                <span class="badge">3</span>
                            </a>

                            <div class="dropdown-menu notification-menu large">
                                <div class="notification-title">
                                    <span class="pull-right label label-default">93</span>
                                    Rede
                                </div>

                                <div class="content">
                                    <ul>
                                        <li>
                                            <p class="clearfix mb-xs">
                                                <span class="message pull-left">Lateralidade</span>
                                            </p>
                                            <span class="badge badge-light">6 pessoas</span>
                                        </li>

                                        <li>
                                            <p class="clearfix mb-xs">
                                                <span class="message pull-left">Profundidade</span>
                                            </p>
                                            <span class="badge badge-primary">87 pessoas</span>
                                        </li>

                                        <li>
                                            <p class="clearfix mb-xs">
                                                <span class="message pull-left">Níveis</span>
                                            </p>
                                            <span class="badge badge-primary">12 níveis</span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </li>-->
<!--                        <li>
                            <a href="#" class="dropdown-toggle notification-icon" data-toggle="dropdown">
                                <i class="icons icon-envelope"></i>
                                <span class="badge">4</span>
                            </a>

                            <div class="dropdown-menu notification-menu">
                                <div class="notification-title">
                                    <span class="pull-right label label-default">230</span>
                                    Messages
                                </div>

                                <div class="content">
                                    <ul>
                                        <li>
                                            <a href="#" class="clearfix">
                                                <figure class="image">
                                                    <img src="assets/images/!sample-user.jpg" alt="Joseph Doe Junior" class="img-circle" />
                                                </figure>
                                                <span class="title">Joseph Doe</span>
                                                <span class="message">Lorem ipsum dolor sit.</span>
                                            </a>
                                        </li>
                                    </ul>

                                    <hr />

                                    <div class="text-right">
                                        <a href="#" class="view-more">View All</a>
                                    </div>
                                </div>
                            </div>
                        </li>-->
<!--                        <li>
                            <a href="#" class="dropdown-toggle notification-icon" data-toggle="dropdown">
                                <i class="fa fa-bell text-warning"></i>
                                <span class="badge">3</span>
                            </a>

                            <div class="dropdown-menu notification-menu">
                                <div class="notification-title">
                                    <span class="pull-right label label-default">3</span>
                                    Alerts
                                </div>

                                <div class="content">
                                    <ul>
                                        <li>
                                            <a href="#" class="clearfix">
                                                <div class="image">
                                                    <i class="fa fa-thumbs-down bg-danger"></i>
                                                </div>
                                                <span class="title">Server is Down!</span>
                                                <span class="message">Just now</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" class="clearfix">
                                                <div class="image">
                                                    <i class="fa fa-lock bg-warning"></i>
                                                </div>
                                                <span class="title">User Locked</span>
                                                <span class="message">15 minutes ago</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" class="clearfix">
                                                <div class="image">
                                                    <i class="fa fa-signal bg-success"></i>
                                                </div>
                                                <span class="title">Connection Restaured</span>
                                                <span class="message">10/10/2016</span>
                                            </a>
                                        </li>
                                    </ul>

                                    <hr />

                                    <div class="text-right">
                                        <a href="#" class="view-more">View All</a>
                                    </div>
                                </div>
                            </div>
                        </li>-->
                    </ul>

                    <span class="separator"></span>

                    <div id="userbox" class="userbox">
                        <a href="#" data-toggle="dropdown">
                            <figure class="profile-picture">
                                <img src="{{asset('assets/images/!logged-user.jpg')}}" alt="{{Auth::user()->name}}" class="img-circle" data-lock-picture="{{asset('assets/images/!logged-user.jpg')}}" />
                            </figure>
                            <div class="profile-info" data-lock-name="{{Auth::user()->name}}" data-lock-email="{{Auth::user()->email}}">
                                <span class="name">{{Auth::user()->name}}</span>
                                <span class="role">
                                    @if(count(Auth::user()->getRoleNames()) > 0)
                                        {{Auth::user()->getRoleNames()[0]}}
                                    @endif
                                </span>
                            </div>

                            <i class="fa custom-caret"></i>
                        </a>

                        <div class="dropdown-menu">
                            <ul class="list-unstyled">
                                <li class="divider"></li>
                                <li>
                                    <a role="menuitem" tabindex="-1" href="{{route('profile')}}"><i class="fa fa-user"></i> {{trans('general.my_profile')}}</a>
                                </li>			
                                <li>
                                    <a role="menuitem" tabindex="-1" href="#" data-lock-screen="true"><i class="fa fa-lock"></i> Lock Screen</a>
                                </li>
                                <li>
                                    <a role="menuitem" 
                                       tabindex="-1" 
                                       href="{{ route('logout') }}" 
                                       onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                        <i class="fa fa-power-off"></i> {{trans('general.logout')}}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>                                    
                                </li>
                            </ul>
                        </div>
                    </div>                
                </div>                
                <!-- end: search & user box -->
                    
                @endif
                
            </header>
            <!-- end: header -->

resources/views/layouts/login.blade.php
<!doctype html>
<html class="fixed" lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    @include('layouts/head')
    <body class="login">
        @yield('content')
    @include('layouts/footer')
    </body>
</html>

resources/views/layouts/sidebar.blade.php
                <!-- start: sidebar -->
                <aside id="sidebar-left" class="sidebar-left">

                    <div class="sidebar-header">
                        <div class="sidebar-title">
                            Menu Principal
                        </div>
                        <div class="sidebar-toggle hidden-xs" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
                            <i class="fa fa-bars" aria-label="Toggle sidebar"></i>
                        </div>
                    </div>

                    <div class="nano">
                        <div class="nano-content">
                            <nav id="menu" class="nav-main" role="navigation">

                                <ul class="nav nav-main">
                                    <li class="{{ Request::is('home*') ? 'nav-active' : '' }}">
                                        <a href="{{route('home')}}">
                                            <i class="icons icon-chart" aria-hidden="true"></i>
                                            <span>Dashboard</span>
                                        </a>                        
                                    </li>
                                    @can(['user-list'])
                                    <li class="nav-parent {{ Request::is('users*') ? 'nav-expanded nav-active' : '' }}">
                                        <a href="#">
                                            <i class="icon icon-people" aria-hidden="true"></i>
                                            <span>{{trans('general.management.users')}}</span>
                                        </a>
                                        <ul class="nav nav-children">
                                            @can(['user-list'])
                                            <li class="{{ Request::is('users*') && !Request::is('users/create') ? 'nav-active' : '' }}">
                                                <a href="{{route('users.index')}}">
                                                    {{trans('general.list')}}
                                                </a>
                                            </li>
                                            @endcan
                                            @can(['user-create'])
                                            <li class="{{ Request::is('users/create') ? 'nav-active' : '' }}">
                                                <a href="{{route('users.create')}}">
                                                    {{trans('general.management.new_user')}}
                                                </a>
                                            </li>
                                            @endcan
                                        </ul>
                                    </li>
                                    @endcan
                                    @can(['product-list'])
                                    <li class="nav-parent {{ Request::is('products*') ? 'nav-expanded nav-active' : '' }}">
                                        <a href="#">
                                            <i class="icon icon-briefcase" aria-hidden="true"></i>
                                            <span>{{trans('general.management.products')}}</span>
                                        </a>
                                        <ul class="nav nav-children">
                                            @can(['product-list'])
                                            <li class="{{ Request::is('products*') && !Request::is('products/create') ? 'nav-active' : '' }}">
                                                <a href="{{route('products.index')}}">
                                                    {{trans('general.list')}}
                                                </a>
                                            </li>
                                            @endcan
                                            @can(['product-create'])
                                            <li class="{{ Request::is('products/create') ? 'nav-active' : '' }}">
                                                <a href="{{route('products.create')}}">
                                                    {{trans('general.management.new_product')}}
                                                </a>
                                            </li>
                                            @endcan
                                        </ul>
                                    </li>
                                    @endcan
                                    @can(['role-list', 'role-create'])
                                    <li class="nav-parent {{ Request::is('roles*') ? 'nav-expanded nav-active' : '' }}">
                                        <a href="#">
                                            <i class="icon icon-layers" aria-hidden="true"></i>
                                            <span>{{trans('general.management.roles')}}</span>
                                        </a>
                                        <ul class="nav nav-children">
                                            @can('role-list')
                                            <li class="{{ Request::is('roles*') && !Request::is('roles/create') ? 'nav-active' : '' }}">
                                                <a href="{{route('roles.index')}}">
                                                    {{trans('general.list')}}
                                                </a>
                                            </li>
                                            @endcan
                                            @can('role-create')
                                            <li class="{{ Request::is('roles/create') ? 'nav-active' : '' }}">
                                                <a href="{{route('roles.create')}}">
                                                    {{trans('general.management.new_role')}}
                                                </a>
                                            </li>
                                            @endcan
                                        </ul>
                                    </li>
                                    @endcan
                                    @can(['network-list'])
                                    <li class="nav-parent {{ Request::is('network*') ? 'nav-expanded nav-active' : '' }}">
                                        <a href="#">
                                            <i class="icon icon-people" aria-hidden="true"></i>
                                            <span>{{trans('general.management.network')}}</span>
                                        </a>
                                        <ul class="nav nav-children">
                                            @can('network-list')
                                            <li class="{{ Request::is('network*') && !Request::is('network/create') && !Request::is('network/distribution')? 'nav-active' : '' }}">
                                                <a href="{{route('network.laterality')}}">
                                                    {{trans('network.laterality')}}
                                                </a>
                                            </li>
                                            @endcan
                                            @can('network-list')
                                            <li class="{{ Request::is('network/distribution') ? 'nav-active' : '' }}">
                                                <a href="{{route('network.distribution')}}">
                                                    {{trans('network.distribution')}}
                                                </a>
                                            </li>
                                            @endcan                                            
                                            @can('network-create')
                                            <li class="{{ Request::is('network/create') ? 'nav-active' : '' }}">
                                                <a href="{{route('network.create')}}">
                                                    {{trans('general.management.new_affiliate')}}
                                                </a>
                                            </li>
                                            @endcan
                                        </ul>
                                    </li>
                                    @endcan
                                    @can(['network-list'])
                                    <li class="nav nav-main {{ Request::is('settings*') ? 'nav-expanded nav-active' : '' }}">
                                        <a href="{{route('settings.index')}}">
                                            <i class="icon icon-settings" aria-hidden="true"></i>
                                            <span>{{trans('general.management.settings')}}</span>
                                        </a>
                                    </li>
                                    @endcan
                                </ul>
                            </nav>
                        </div>

                        <script>
                            // Maintain Scroll Position
                            if (typeof localStorage !== 'undefined') {
                                if (localStorage.getItem('sidebar-left-position') !== null) {
                                    var initialPosition = localStorage.getItem('sidebar-left-position'),
                                            sidebarLeft = document.querySelector('#sidebar-left .nano-content');
                                    sidebarLeft.scrollTop = initialPosition;
                                }
                            }
                        </script>

                    </div>

                </aside>
                <!-- end: sidebar -->